
const topics = [
  "asigurare-viata-moldova",
  "asigurare-agricola-seceta",
  "asigurare-cyber-companii",
  "asigurare-raspundere-profesionala",
  "asigurare-cargo-transport-marfa",
  "asigurare-sanatate-privata",
  "asigurare-animale-companie",
  "asigurare-echipamente-it",
  "asigurare-evenimente-corporate",
  "asigurare-constructii-montaj",
  "asigurare-flota-auto",
  "asigurare-accidente-angajati",
  "asigurare-drone-comerciale",
  "asigurare-pierdere-profit",
  "asigurare-raspundere-directori",
  "asigurare-panouri-fotovoltaice",
  "asigurare-storno-calatorie",
  "asigurare-biciclete-trotinete",
  "asigurare-obiecte-arta",
  "asigurare-riscuri-cibernetice-imm",
  "asigurare-raspundere-civila-generala",
  "asigurare-rca-moldova",
  "asigurare-casco-moldova",
  "asigurare-carte-verde",
  "asigurare-locuinta-moldova",
  "asigurare-medicala-calatorii",
  "asigurare-malpraxis-medical",
  "asigurare-raspundere-civila-auto",
  "asigurare-bunuri-tranzit",
  "asigurare-utilaje-industriale",
  "asigurare-depozite-logistice",
  "asigurare-riscuri-politice",
  "asigurare-credit-comercial",
  "asigurare-garantii-licitatie",
  "asigurare-buna-executie",
  "asigurare-mentenanta-proiecte",
  "asigurare-raspundere-civila-legala",
  "asigurare-protectie-juridica",
  "asigurare-asistenta-rutiera",
  "asigurare-bagaje-calatorie",
  "asigurare-anulare-eveniment",
  "asigurare-raspundere-civila-familie",
  "asigurare-cladiri-birouri",
  "asigurare-centre-comerciale",
  "asigurare-hoteluri-pensiuni",
  "asigurare-restaurante-cafenele",
  "asigurare-saloane-infrumusetare",
  "asigurare-clinici-private",
  "asigurare-scoli-gradinite",
  "asigurare-sali-fitness",
  "asigurare-depozite-cereale",
  "asigurare-livezi-viticultura",
  "asigurare-ferme-zootehnice",
  "asigurare-serre-solarii",
  "asigurare-sisteme-irigatii",
  "asigurare-parcuri-eoliene",
  "asigurare-biogaz-biomasa",
  "asigurare-hidrocentrale-mici",
  "asigurare-stocare-energie",
  "asigurare-infrastructura-critica",
  "asigurare-poduri-tuneluri",
  "asigurare-drumuri-autostrazi",
  "asigurare-retele-electrice",
  "asigurare-conducte-gaz-apa",
  "asigurare-telecomunicatii",
  "asigurare-centre-date",
  "asigurare-software-as-a-service",
  "asigurare-e-commerce",
  "asigurare-fintech-banking",
  "asigurare-cripto-active",
  "asigurare-raspundere-civila-it",
  "asigurare-eroare-omisiune",
  "asigurare-infidelitate-angajati",
  "asigurare-bani-tranzit",
  "asigurare-seifuri-valori",
  "asigurare-expozitii-targuri",
  "asigurare-concerte-festivaluri",
  "asigurare-competitii-sportive",
  "asigurare-raspundere-civila-sportivi",
  "asigurare-yachturi-ambarcatiuni",
  "asigurare-avioane-private",
  "asigurare-elicoptere-utilitare",
  "asigurare-raspundere-civila-aeroportuara",
  "asigurare-maritima-hull",
  "asigurare-protectie-indemnizatie",
  "asigurare-riscuri-catastrofale",
  "asigurare-terorism-sabotaj",
  "asigurare-raspundere-civila-poluare",
  "asigurare-remediere-mediu",
  "asigurare-raspundere-civila-produs",
  "asigurare-rechemare-produs",
  "asigurare-studii-clinice",
  "asigurare-raspundere-civila-angajator",
  "asigurare-sanatate-expatriati",
  "asigurare-repatriere-deces",
  "asigurare-asistenta-medicala-vip",
  "asigurare-boli-grave",
  "asigurare-spitalizare-interventii",
  "asigurare-stomatologica-corporate",
  "asigurare-optica-medicala",
  "asigurare-maternitate-nastere",
  "asigurare-kinetoterapie-recuperare",
  "asigurare-sanatate-mentala",
  "asigurare-check-up-anual",
  "asigurare-viata-credit-ipotecar",
  "asigurare-viata-protectie-familie",
  "asigurare-viata-economisire",
  "asigurare-viata-studii-copii",
  "asigurare-viata-pensie-privata",
  "asigurare-viata-keyman",
  "asigurare-viata-parteneri-afaceri",
  "asigurare-viata-succesiune",
  "asigurare-viata-donatii-caritate",
  "asigurare-viata-unit-linked",
  "asigurare-viata-term-life",
  "asigurare-viata-whole-life",
  "asigurare-viata-anuitati",
  "asigurare-viata-invaliditate-permanenta",
  "asigurare-viata-scutire-prime",
  "asigurare-viata-clauze-suplimentare",
  "asigurare-viata-beneficiari",
  "asigurare-viata-fiscalitate-moldova",
  "asigurare-viata-reducere-impozit",
  "asigurare-viata-avantaje-angajator",
  "asigurare-viata-fidelizare-angajati",
  "asigurare-viata-pachete-executive",
  "asigurare-viata-grup-corporate",
  "asigurare-viata-microasigurari",
  "asigurare-viata-incluziune-financiara",
  "asigurare-viata-educatie-financiara",
  "asigurare-viata-mituri-realitati",
  "asigurare-viata-cum-alegi-brokerul",
  "asigurare-viata-ing-broker-expertiza",
  "asigurare-viata-daune-procedura",
  "asigurare-viata-documente-necesare",
  "asigurare-viata-termeni-cheie",
  "asigurare-viata-dictionar-asigurari",
  "asigurare-viata-legislatie-moldova",
  "asigurare-viata-cnpf-reglementari",
  "asigurare-viata-piata-moldova-2026",
  "asigurare-viata-tendinte-globale",
  "asigurare-viata-digitalizare-insurtech",
  "asigurare-viata-aplicatii-mobile",
  "asigurare-viata-easigurari-com",
  "asigurare-viata-suport-clienti",
  "asigurare-viata-recomandari-experti",
  "asigurare-viata-studii-caz",
  "asigurare-viata-testimoniale-clienti",
  "asigurare-viata-blog-ing-broker",
  "asigurare-viata-noutati-piata",
  "asigurare-viata-evenimente-seminarii",
  "asigurare-viata-webinare-gratuite",
  "asigurare-viata-ghid-incepatori",
  "asigurare-viata-ghid-avansati",
  "asigurare-viata-ghid-corporate",
  "asigurare-viata-ghid-imm",
  "asigurare-viata-ghid-startups",
  "asigurare-viata-ghid-freelancers",
  "asigurare-viata-ghid-it-professionals",
  "asigurare-viata-ghid-agricultori",
  "asigurare-viata-ghid-transportatori",
  "asigurare-viata-ghid-constructori",
  "asigurare-viata-ghid-medici",
  "asigurare-viata-ghid-avocati",
  "asigurare-viata-ghid-contabili",
  "asigurare-viata-ghid-arhitecti",
  "asigurare-viata-ghid-ingineri",
  "asigurare-viata-ghid-expatriati",
  "asigurare-viata-ghid-diaspora",
  "asigurare-viata-ghid-investitori",
  "asigurare-viata-ghid-manageri",
  "asigurare-viata-ghid-hr-managers",
  "asigurare-viata-ghid-cfo",
  "asigurare-viata-ghid-ceo",
  "asigurare-viata-ghid-antreprenori",
  "asigurare-viata-ghid-familie",
  "asigurare-viata-ghid-copii",
  "asigurare-viata-ghid-seniori",
  "asigurare-viata-ghid-tineri",
  "asigurare-viata-ghid-studenti",
  "asigurare-viata-ghid-sportivi",
  "asigurare-viata-ghid-calatori",
  "asigurare-viata-ghid-soferi",
  "asigurare-viata-ghid-proprietari-case",
  "asigurare-viata-ghid-proprietari-apartamente",
  "asigurare-viata-ghid-proprietari-afaceri",
  "asigurare-viata-ghid-asigurari-obligatorii",
  "asigurare-viata-ghid-asigurari-facultative",
  "asigurare-viata-ghid-reasigurari",
  "asigurare-viata-ghid-fronting",
  "asigurare-viata-ghid-claims-management",
  "asigurare-viata-ghid-risk-management",
  "asigurare-viata-ghid-audit-asigurari",
  "asigurare-viata-ghid-optimizare-costuri",
  "asigurare-viata-ghid-alegere-asigurator",
  "asigurare-viata-ghid-ing-broker-servicii",
  "asigurare-viata-ghid-contact-suport"
];

const generateTopics = () => {
  return topics.map(slug => {
    const base = slug.replace(/-/g, ' ');
    const titleRo = base.charAt(0).toUpperCase() + base.slice(1) + ': Ghid complet pentru Moldova';
    const titleRu = base.charAt(0).toUpperCase() + base.slice(1) + ': Полное руководство для Молдовы';
    const titleEn = base.charAt(0).toUpperCase() + base.slice(1) + ': Complete guide for Moldova';
    
    let tag = 'Asigurare';
    if (slug.includes('viata')) tag = 'Viață';
    else if (slug.includes('agricola')) tag = 'Agricultură';
    else if (slug.includes('cyber')) tag = 'Cyber';
    else if (slug.includes('it')) tag = 'IT';
    else if (slug.includes('auto')) tag = 'Auto';
    else if (slug.includes('constructii')) tag = 'Construcții';
    else if (slug.includes('sanatate')) tag = 'Sănătate';
    else if (slug.includes('calatorie')) tag = 'Călătorie';
    else if (slug.includes('business')) tag = 'Business';
    else if (slug.includes('energie')) tag = 'Energie';
    
    return { slug, titleRo, titleRu, titleEn, tag };
  });
};

console.log(JSON.stringify(generateTopics(), null, 2));
